#!/bin/bash
alias copy="command wl-copy"
alias uncopy="command wl-copy < /dev/null"
alias paste="command wl-paste"
alias lower="command tr '[:upper:]' '[:lower:]'"
alias upper="command tr '[:lower:]' '[:upper:]'"
alias ssh-tmp="command ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR"
