#!/bin/bash
# Reset
COLOR_NO_COLOUR='\e[0m'

# Regular Colors
COLOR_BLACK='\e[0;30m'
COLOR_GRAY='\e[1;30m'
COLOR_LIGHT_GRAY='\e[0;37m'
COLOR_CYAN='\e[0;36m'
COLOR_LIGHT_CYAN='\e[1;36m'
COLOR_BLUE='\e[0;34m'
COLOR_LIGHT_BLUE='\e[1;34m'
COLOR_RED='\e[0;31m'
COLOR_LIGHT_RED='\e[1;31m'
COLOR_GREEN='\e[0;32m'
COLOR_LIGHT_GREEN='\e[1;32m'
COLOR_PURPLE='\e[0;35m'
COLOR_LIGHT_PURPLE='\e[1;35m'
COLOR_BROWN='\e[0;33m'
COLOR_YELLOW='\e[1;33m'
COLOR_WHITE='\e[0;37m'

# Bold
COLOR_B_BLACK='\e[1;30m'       # Black
COLOR_B_RED='\e[1;31m'         # Red
COLOR_B_GREEN='\e[1;32m'       # Green
COLOR_B_YELLOW='\e[1;33m'      # Yellow
COLOR_B_BLUE='\e[1;34m'        # Blue
COLOR_B_PURPLE='\e[1;35m'      # Purple
COLOR_B_CYAN='\e[1;36m'        # Cyan
COLOR_B_WHITE='\e[1;37m'       # White

# Underline
COLOR_U_BLACK='\e[4;30m'       # Black
COLOR_U_RED='\e[4;31m'         # Red
COLOR_U_GREEN='\e[4;32m'       # Green
COLOR_U_YELLOW='\e[4;33m'      # Yellow
COLOR_U_BLUE='\e[4;34m'        # Blue
COLOR_U_PURPLE='\e[4;35m'      # Purple
COLOR_U_CYAN='\e[4;36m'        # Cyan
COLOR_U_WHITE='\e[4;37m'       # White

# Background
COLOR_BG_BLACK='\e[40m'       # Black
COLOR_BG_RED='\e[41m'         # Red
COLOR_BG_GREEN='\e[42m'       # Green
COLOR_BG_YELLOW='\e[43m'      # Yellow
COLOR_BG_BLUE='\e[44m'        # Blue
COLOR_BG_PURPLE='\e[45m'      # Purple
COLOR_BG_CYAN='\e[46m'        # Cyan
COLOR_BG_WHITE='\e[47m'       # White

# High Intensity
COLOR_HI_BLACK='\e[0;90m'       # Black
COLOR_HI_RED='\e[0;91m'         # Red
COLOR_HI_GREEN='\e[0;92m'       # Green
COLOR_HI_YELLOW='\e[0;93m'      # Yellow
COLOR_HI_BLUE='\e[0;94m'        # Blue
COLOR_HI_PURPLE='\e[0;95m'      # Purple
COLOR_HI_CYAN='\e[0;96m'        # Cyan
COLOR_HI_WHITE='\e[0;97m'       # White

# Bold High Intensity
COLOR_BHI_BLACK='\e[1;90m'      # Black
COLOR_BHI_RED='\e[1;91m'        # Red
COLOR_BHI_GREEN='\e[1;92m'      # Green
COLOR_BHI_YELLOW='\e[1;93m'     # Yellow
COLOR_BHI_BLUE='\e[1;94m'       # Blue
COLOR_BHI_PURPLE='\e[1;95m'     # Purple
COLOR_BHI_CYAN='\e[1;96m'       # Cyan
COLOR_BHI_WHITE='\e[1;97m'      # White

# High Intensity backgrounds
COLOR_BG_HI_BLACK='\e[0;100m'   # Black
COLOR_BG_HI_RED='\e[0;101m'     # Red
COLOR_BG_HI_GREEN='\e[0;102m'   # Green
COLOR_BG_HI_YELLOW='\e[0;103m'  # Yellow
COLOR_BG_HI_BLUE='\e[0;104m'    # Blue
COLOR_BG_HI_PURPLE='\e[10;95m'  # Purple
COLOR_BG_HI_CYAN='\e[0;106m'    # Cyan
COLOR_BG_HI_WHITE='\e[0;107m'   # White

git_prompt() {
    if git rev-parse --git-dir > /dev/null 2>&1; then 
        BRANCH="$(git branch 2>/dev/null | grep "^*" | colrm 1 2)"

        if [ ! -z "${BRANCH}" ]; then 
            echo -ne " ${COLOR_BHI_PURPLE}git@${BRANCH}"
        else
            echo -ne " ${COLOR_BHI_PURPLE}git"
        fi
    fi
}

exit_status() {
    EXIT_CODE="$?"

    if [ "$EXIT_CODE" -ne 0 ]; then
        echo -ne " ${COLOR_BG_HI_RED}${COLOR_B_BLACK} ${EXIT_CODE} ${COLOR_NO_COLOUR}"
    fi
}

PS1="${COLOR_BHI_GREEN}\u${COLOR_BHI_WHITE}@${COLOR_BHI_GREEN}\h "
PS1+="${FG_CYAN}\w"
PS1+="${COLOR_NO_COLOUR}\$(exit_status)\$(git_prompt)"
PS1+=" ${COLOR_BHI_YELLOW}\$"
PS1+="\[$(tput sgr0)\] "
export PS1