#!/bin/bash
# Reset
COLOR_NO_COLOUR='\001\e[0m\002'

# Regular Colors
COLOR_BLACK='\001\e[0;30m\002'
COLOR_GRAY='\001\e[1;30m\002'
COLOR_LIGHT_GRAY='\001\e[0;37m\002'
COLOR_CYAN='\001\e[0;36m\002'
COLOR_LIGHT_CYAN='\001\e[1;36m\002'
COLOR_BLUE='\001\e[0;34m\002'
COLOR_LIGHT_BLUE='\001\e[1;34m\002'
COLOR_RED='\001\e[0;31m\002'
COLOR_LIGHT_RED='\001\e[1;31m\002'
COLOR_GREEN='\001\e[0;32m\002'
COLOR_LIGHT_GREEN='\001\e[1;32m\002'
COLOR_PURPLE='\001\e[0;35m\002'
COLOR_LIGHT_PURPLE='\001\e[1;35m\002'
COLOR_BROWN='\001\e[0;33m\002'
COLOR_YELLOW='\001\e[1;33m\002'
COLOR_WHITE='\001\e[0;37m\002'

# Bold
COLOR_B_BLACK='\001\e[1;30m\002'       # Black
COLOR_B_RED='\001\e[1;31m\002'         # Red
COLOR_B_GREEN='\001\e[1;32m\002'       # Green
COLOR_B_YELLOW='\001\e[1;33m\002'      # Yellow
COLOR_B_BLUE='\001\e[1;34m\002'        # Blue
COLOR_B_PURPLE='\001\e[1;35m\002'      # Purple
COLOR_B_CYAN='\001\e[1;36m\002'        # Cyan
COLOR_B_WHITE='\001\e[1;37m\002'       # White

# Underline
COLOR_U_BLACK='\001\e[4;30m\002'       # Black
COLOR_U_RED='\001\e[4;31m\002'         # Red
COLOR_U_GREEN='\001\e[4;32m\002'       # Green
COLOR_U_YELLOW='\001\e[4;33m\002'      # Yellow
COLOR_U_BLUE='\001\e[4;34m\002'        # Blue
COLOR_U_PURPLE='\001\e[4;35m\002'      # Purple
COLOR_U_CYAN='\001\e[4;36m\002'        # Cyan
COLOR_U_WHITE='\001\e[4;37m\002'       # White

# Background
COLOR_BG_BLACK='\001\e[40m\002'       # Black
COLOR_BG_RED='\001\e[41m\002'         # Red
COLOR_BG_GREEN='\001\e[42m\002'       # Green
COLOR_BG_YELLOW='\001\e[43m\002'      # Yellow
COLOR_BG_BLUE='\001\e[44m\002'        # Blue
COLOR_BG_PURPLE='\001\e[45m\002'      # Purple
COLOR_BG_CYAN='\001\e[46m\002'        # Cyan
COLOR_BG_WHITE='\001\e[47m\002'       # White

# High Intensity
COLOR_HI_BLACK='\001\e[0;90m\002'       # Black
COLOR_HI_RED='\001\e[0;91m\002'         # Red
COLOR_HI_GREEN='\001\e[0;92m\002'       # Green
COLOR_HI_YELLOW='\001\e[0;93m\002'      # Yellow
COLOR_HI_BLUE='\001\e[0;94m\002'        # Blue
COLOR_HI_PURPLE='\001\e[0;95m\002'      # Purple
COLOR_HI_CYAN='\001\e[0;96m\002'        # Cyan
COLOR_HI_WHITE='\001\e[0;97m\002'       # White

# Bold High Intensity
COLOR_BHI_BLACK='\001\e[1;90m\002'      # Black
COLOR_BHI_RED='\001\e[1;91m\002'        # Red
COLOR_BHI_GREEN='\001\e[1;92m\002'      # Green
COLOR_BHI_YELLOW='\001\e[1;93m\002'     # Yellow
COLOR_BHI_BLUE='\001\e[1;94m\002'       # Blue
COLOR_BHI_PURPLE='\001\e[1;95m\002'     # Purple
COLOR_BHI_CYAN='\001\e[1;96m\002'       # Cyan
COLOR_BHI_WHITE='\001\e[1;97m\002'      # White

# High Intensity backgrounds
COLOR_BG_HI_BLACK='\001\e[0;100m\002'   # Black
COLOR_BG_HI_RED='\001\e[0;101m\002'     # Red
COLOR_BG_HI_GREEN='\001\e[0;102m\002'   # Green
COLOR_BG_HI_YELLOW='\001\e[0;103m\002'  # Yellow
COLOR_BG_HI_BLUE='\001\e[0;104m\002'    # Blue
COLOR_BG_HI_PURPLE='\001\e[10;95m\002'  # Purple
COLOR_BG_HI_CYAN='\001\e[0;106m\002'    # Cyan
COLOR_BG_HI_WHITE='\001\e[0;107m\002'   # White

git_prompt() {
    if git rev-parse --git-dir > /dev/null 2>&1; then 
        BRANCH="$(git branch 2>/dev/null | grep "^*" | colrm 1 2)"

        if [ ! -z "${BRANCH}" ]; then 
            echo -ne " ${COLOR_BHI_PURPLE}git@${BRANCH}"
        else
            echo -ne " ${COLOR_BHI_PURPLE}git"
        fi
    fi
}

exit_status() {
    EXIT_CODE="$?"

    if [ "$EXIT_CODE" -ne 0 ]; then
        echo -ne " ${COLOR_BG_HI_RED}${COLOR_B_BLACK} ${EXIT_CODE} ${COLOR_NO_COLOUR}"
    fi
}

PS1="${COLOR_BHI_GREEN}\u${COLOR_BHI_WHITE}@${COLOR_BHI_GREEN}\h "
PS1+="${COLOR_BHI_CYAN}\w"
PS1+="${COLOR_NO_COLOUR}\$(exit_status)\$(git_prompt)"
PS1+=" ${COLOR_BHI_YELLOW}\$${COLOR_NO_COLOUR} "
export PS1